import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DOCS_DIR = path.join(__dirname, '../public/docs');
const OUTPUT_FILE = path.join(__dirname, '../src/lib/knowledge_base.js');

// Helper to clean filenames into titles
function formatTitle(filename) {
  // Remove extension
  let name = filename.replace(/\.pdf$/i, '');
  
  // Remove date prefixes like "03-05-2020_v1_"
  name = name.replace(/^\d{2}-\d{2}-\d{4}_v\d+_/, '');
  
  // Replace underscores and dashes with spaces
  name = name.replace(/[_-]/g, ' ');
  
  // Capitalize words
  return name.replace(/\b\w/g, l => l.toUpperCase());
}

// Helper to generate keywords
function generateKeywords(filename) {
  const name = filename.replace(/\.pdf$/i, '').toLowerCase();
  // Split by non-alphanumeric chars
  const words = name.split(/[^a-z0-9]+/);
  // Filter out short words and duplicates
  const unique = [...new Set(words.filter(w => w.length > 2))];
  return unique;
}

// Main generator
function generateKnowledgeBase() {
  console.log("Scanning docs...");
  
  if (!fs.existsSync(DOCS_DIR)) {
    console.error("Docs directory not found!");
    return;
  }

  const files = fs.readdirSync(DOCS_DIR).filter(f => f.toLowerCase().endsWith('.pdf'));
  
  const entries = files.map((file, index) => {
    const title = formatTitle(file);
    const keywords = generateKeywords(file);
    
    return {
      id: `doc-${index}`,
      keywords: keywords,
      title: title,
      type: "document",
      content: `Technical documentation for ${title}.`,
      assets: {
        pdf: `/docs/${file}`,
        thumbnail: `/docs/${file}`
      },
      steps: [] // No manual steps for these auto-generated docs
    };
  });

  // Add the manual entries back (we'll just prepend them for now or keep them separate if we want)
  // For this task, I'll overwrite with the massive list but keep the structure valid.
  
  const fileContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/generate_knowledge.js

export const REPAIR_KNOWLEDGE_BASE = ${JSON.stringify(entries, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`Successfully indexed ${entries.length} documents to ${OUTPUT_FILE}`);
}

generateKnowledgeBase();
